[tool.poetry]
name = "baddns"
version = "0.0.0"
description = "Check subdomains for for subdomain takeovers and other DNS tomfoolery"
authors = ["liquidsec <paul.mueller08@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
include = ["signatures/**/*"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
pyyaml = "^6.0.1"
dnspython = "^2.4.1"
colorama = "^0.4.6"
httpx = "^0.24.1"
python-whois = "^0.8.0"
tldextract = "^3.4.4"
python-dateutil = "^2.8.2"
httpx-cache = "^0.12.0"

[tool.poetry.group.dev.dependencies]
pytest-httpx = "^0.23.1"
pyfakefs = "^5.2.3"
requests-mock = "^1.11.0"
pytest = "^7.4.0"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.21.1"
mock = "^5.1.0"
pytest-mock = "^3.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.poetry.scripts]
baddns = 'baddns.cli:main'

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
