name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --group docs

    - name: Deploy Documentation
      run: uv run mkdocs gh-deploy --force
