name: Read Sources

on:
  workflow_dispatch:
jobs:
  readsources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Checkout remote repository (dnsReaper)
      uses: actions/checkout@v3
      with:
        repository: punk-security/dnsReaper
        path: dnsReaper 

    - name: Checkout remote repository (nuclei-templates)
      uses: actions/checkout@v3
      with:
        repository: projectdiscovery/nuclei-templates
        path: nuclei-templates

    - name: Read Sources
      run: |
        poetry run python3 BadDNS/scripts/readsources.py

    - name: Get file content
      id: getfile
      run: |
        # Only process the first file
        filename=$(ls signatures_to_test | head -n 1)
        content=$(cat signatures_to_test/$filename)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=filename::$filename"
        echo "::set-output name=content::$content" 2>&1 | tee -a readsources_action.log
    
    - name: Stage and commit file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b new-signature-${{ steps.getfile.outputs.filename }} 2>&1 | tee -a readsources_action.log
        git add signatures_to_test/${{ steps.getfile.outputs.filename }} 2>&1 | tee -a readsources_action.log
        git commit -m "Add new signature ${{ steps.getfile.outputs.filename }}" 2>&1 | tee -a readsources_action.log
        git push origin new-signature-${{ steps.getfile.outputs.filename }} 2>&1 | tee -a readsources_action.log
    
    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GH_TOKEN | gh auth login --with-token 2>&1 | tee -a readsources_action.log
        echo "Add new signature ${{ steps.getfile.outputs.filename }}" > pr_message
        echo "This PR adds a new signature:" >> pr_message
        echo "\`\`\`" >> pr_message
        cat signatures_to_test/${{ steps.getfile.outputs.filename }} >> pr_message
        echo "\`\`\`" >> pr_message
        gh pr create --title "Add new signature ${{ steps.getfile.outputs.filename }}" --body-file pr_message --head new-signature-${{ steps.getfile.outputs.filename }} --repo ${{ github.repository }} 2>&1 | tee -a readsources_action.log

    - name: Upload readsources.py log
      uses: actions/upload-artifact@v2
      with:
        name: readsources.py-log
        path: readsources.log

    - name: Upload read-sources action log
      uses: actions/upload-artifact@v2
      with:
        name: read-sources-action-log
        path: readsources_action.log
