name: Read Sources

on:
  workflow_dispatch:
jobs:
  readsources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Checkout (self)
      uses: actions/checkout@v3

    - name: Checkout remote repository (dnsReaper)
      uses: actions/checkout@v3
      with:
        repository: punk-security/dnsReaper
        path: dnsReaper 

    - name: Checkout remote repository (nuclei-templates)
      uses: actions/checkout@v3
      with:
        repository: projectdiscovery/nuclei-templates
        path: nuclei-templates

    - name: Read Sources
      run: |
        poetry run python3 BadDNS/scripts/readsources.py

    - name: Iterate over files and create PRs
      run: |
        for filename in signatures_to_test/*; do
          if [ ! -f "signatures/$(basename $filename)" ] || [ "$(cat "signatures/$(basename $filename)")" != "$(cat $filename)" ]; then
            content=$(cat $filename)
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"

            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add $filename
            git commit -m "Add new signature $(basename $filename)"

            echo "::set-output name=filename::$(basename $filename)"
            echo "::set-output name=content::$content"
            
            # Create PR using GitHub Action
            gh pr create --base main --head new-signature-$(basename $filename) --title "Add new signature $(basename $filename)" --body "This PR adds a new signature:\n\n\`\`\`\n$content\n\`\`\`"

            # Delete processed file
            rm $filename

            # Break the loop after processing one file
            break
          fi
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
