name: Read Sources

on:
  workflow_dispatch:
jobs:
  readsources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Checkout remote repository (dnsReaper)
      uses: actions/checkout@v3
      with:
        repository: punk-security/dnsReaper
        path: dnsReaper 

    - name: Checkout remote repository (nuclei-templates)
      uses: actions/checkout@v3
      with:
        repository: projectdiscovery/nuclei-templates
        path: nuclei-templates

    - name: Read Sources
      run: |
        poetry run python3 BadDNS/scripts/readsources.py

    - name: Stage, commit and create PR for changed files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "starting Read Sources run" >> readsources_action.log 
        echo $GH_TOKEN | gh auth login --with-token
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Only process the first file
        files=$(git diff --name-only origin/main | grep signatures_to_test | head -n 1)

        for filename in $files; do
          echo "parsing signature file: $filename" >> readsources_action.log
          echo "checking out new branch new-signature-$filename" >> readsources_action.log
          git checkout -b new-signature-$filename
          git add $filename
          echo "adding commit and pushing branch..." >> readsources_action.log
          git commit -m "Add new signature $filename" && {
            git push origin new-signature-$filename
            echo "Add new signature $filename" > pr_message
            echo "This PR adds a new signature:" >> pr_message
            echo "\`\`\`" >> pr_message
            cat $filename >> pr_message
            echo "\`\`\`" >> pr_message
            echo "creating PR: 'Add new signature $filename'" >> readsources_action.log
            gh pr create --title "Add new signature $filename" --body-file pr_message --head new-signature-$filename --repo ${{ github.repository }}
          }
        done
        echo "completed read sources" >> readsources_action.log

    - name: Upload readsources.py log
      uses: actions/upload-artifact@v2
      with:
        name: readsources.py-log
        path: readsources.log

    - name: Upload read-sources action log
      uses: actions/upload-artifact@v2
      with:
        name: read-sources-action-log
        path: readsources_action.log
