name: Read Sources

on:
  workflow_dispatch:
jobs:
  readsources:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Test
      run: |
        run: python3 scripts/readsources.py

