name: Signature Test

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  signature-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for specific string in PR title and creator
        id: check_conditions
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pr_creator="${{ github.event.pull_request.user.login }}"
          echo "Pull Request title: $pr_title" > signaturetest.log
          echo "Pull Request creator: $pr_creator" >> signaturetest.log
          if [[ "$pr_title" == *"new signature"* && "$pr_creator" == "github-actions[bot]" ]]; then
            echo "::set-output name=is_new_signature_pr::true"
            echo "PR $pr_title Qualified" >> signaturetest.log
          else
            echo "::set-output name=is_new_signature_pr::false"
            echo "PR $pr_title NOT Qualified" >> signaturetest.log
          fi

      - name: Analyze Signature
        id: analyze
        if: steps.check_conditions.outputs.is_new_signature_pr == 'true'
        run: |
            # This is a placeholder for your analysis script
            echo "Running test against signature..." >> signaturetest.log
            echo "::set-output name=result::placeholder result" >> signaturetest.log
            # You can run your test script here

      - name: Add PR comment
        uses: actions/github-script@v3
        if: steps.check_conditions.outputs.is_new_signature_pr == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const event = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
            const issue_number = event.pull_request.number;
            const message = `The analysis completed with the following results: \n\n${{ steps.analyze.outputs.result }}`;
            console.log(`Attempting to add comment for ${issue_number}`);
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
            });




      - name: Upload Signature Test Log
        uses: actions/upload-artifact@v2
        with:
          name: signature-test-log
          path: signaturetest.log
