name: Pull Request Analysis

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check for specific string in PR title and creator
      id: check_conditions
      run: |
        pr_title="${{ github.event.pull_request.title }}"
        pr_creator="${{ github.event.pull_request.user.login }}"
        if [[ "$pr_title" == *"new-signature"* && "$pr_creator" == "github-actions" ]]; then
          echo "::set-output name=is_new_signature_pr::true"
        else
          echo "::set-output name=is_new_signature_pr::false"
        fi

    - name: Analyze pull request
      id: analyze
      run: |
        if [[ "${{ steps.check_conditions.outputs.is_new_signature_pr }}" == "true" ]]; then
          # This is a placeholder for your analysis script
          echo "Running analysis..."
          echo "::set-output name=result::placeholder analysis"
          # You can run your test script here
        fi

    - name: Add PR comment
      uses: actions/github-script@v5
      if: steps.check_conditions.outputs.is_new_signature_pr == 'true'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { pull_request: { number: issue_number } } = context;
          const message = `The analysis completed with the following results: \n\n${{ steps.analyze.outputs.result }}`;
          github.issues.createComment({
            issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
