name: tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  python:
    if: ${{ !contains(github.event.pull_request.title, 'SignatureBot') }}
    uses: blacklanternsecurity/CLA/.github/workflows/python-tests.yml@40c6e18c0a6e32116eea4f89fc826f53c70889dc # main
    with:
      pytest-args: --exitfirst --disable-warnings --log-cli-level=DEBUG --cov-report xml:cov.xml --cov=baddns
      coverage: true
    secrets: inherit
